### ISSUE TITLE
datatype should be parat of param, not handler

### ISSUE THREAD

**Issue by krux02** [HPAC/TTC-C#5]
with `ttc_set_opt` I can set the dataType as a parameter of the handle. Assuming that there is only one handle around, this is like a global state. I don't think this is a very wise idea, because as soon as I have code that uses functions with different dataTypes, I have to set the datatype before any call into ttc. If I forget it anywhere, this code could be broken anytime because it depends on some global state which is not constant. I could even lead to some defensive code that queries the dataType parameter, changes it calls into tcc and then reverts it back, just to ensure that no code could potentially be broken.

This could completely be avoided, by simply putting datatype into the param.

**Comment by tongsucn** [comment]
@krux02 Thanks for your advice. The `datatype` will be moved into `ttc_param_s` in next version. After that, you need set the `datatype` member in `ttc_param_s` object to specify the data type.

In addition, the function `ttc_default_param` will generate a default `ttc_param_s` object whose `datatype` member's value is `TTC_TYPE_DEFAULT`.
